CREATE TABLE PRODUCTO (
	IDPROD 		INTEGER 	NOT NULL
							UNIQUE,
	NOMPROD 	VARCHAR(10) NOT NULL
							UNIQUE,
	PRECIO 		DECIMAL(4,2),
	CANTIDAD 	NUMERIC(2),
	PRIMARY KEY(IDPROD,NOMPROD)
);

CREATE TABLE CLIENTE (
    DNI        VARCHAR (9)  NOT NULL
    						UNIQUE,
    NOMCLIENTE VARCHAR (25) NOT NULL,
    TELEFONO   VARCHAR (9),
    CORREO     VARCHAR (30)
    PRIMARY KEY(DNI,CLIENTE)
);
